version: '3'
volumes:
  data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_DATABASE}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"



  # Start mailhog
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "8026:1025"
      - "8027:8025"
    restart: always
