version: '3'

services:
  # Start MySQL, and ensure that data is stored to a mounted volume
  mysql:
    image: 'mysql:latest'  # You can specify a specific version if needed
    ports:
      - "3306:3306"  # Expose MySQL port if necessary
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
      MYSQL_DATABASE: ${MYSQL_DB}
      # MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
        - /db-data/mysql



  #  start mailhog
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always

